const recipes = [
  {
    id: 1,
    image: "https://via.placeholder.com/150",
    title: "Panda Express Orange Chicken",
    time: "25 minutes",
    servings: "8",
    tags: [],
  },
  {
    id: 2,
    image: "https://via.placeholder.com/150",
    title: "Strawberry Brown Bread",
    time: "25 minutes",
    servings: "10",
    tags: [],
  },
  {
    id: 3,
    image: "https://via.placeholder.com/150",
    title: "Jamaican Beans & Peas",
    time: "25 minutes",
    servings: "12",
    tags: ["Vegan", "Vegetarian", "Gluten Free"],
  },
  {
    id: 4,
    image: "https://via.placeholder.com/150",
    title: "Chocolate Chip Peanut Butter Oatmeal",
    time: "25 minutes",
    servings: "4",
    tags: [],
  },
  {
    id: 5,
    image: "https://via.placeholder.com/150",
    title: "Old Fashioned Oatmeal Raisins",
    time: "25 minutes",
    servings: "8",
    tags: ["Vegan", "Vegetarian"],
  },
  {
    id: 6,
    image: "https://via.placeholder.com/150",
    title: "Old Fashioned Oatmeal Raisins",
    time: "25 minutes",
    servings: "8",
    tags: ["Vegan", "Vegetarian"],
  },
  {
    id: 7,
    image: "https://via.placeholder.com/150",
    title: "Old Fashioned Oatmeal Raisins",
    time: "25 minutes",
    servings: "8",
    tags: ["Vegan", "Vegetarian"],
  },
  {
    id: 8,
    image: "https://via.placeholder.com/150",
    title: "Old Fashioned Oatmeal Raisins",
    time: "25 minutes",
    servings: "8",
    tags: ["Vegan", "Vegetarian"],
  },
  {
    id: 9,
    image: "https://via.placeholder.com/150",
    title: "Old Fashioned Oatmeal Raisins",
    time: "25 minutes",
    servings: "8",
    tags: ["Vegan", "Vegetarian"],
  },
  {
    id: 10,
    image: "https://via.placeholder.com/150",
    title: "Old Fashioned Oatmeal Raisins",
    time: "25 minutes",
    servings: "8",
    tags: ["Vegan", "gluten-free", "Vegetarian"],
  },
];

export default recipes;
